apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vcuxx5mzv-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:dc459046d95b6c7f2af478b12c9a05a7803dbcce@sha256:d2503971d4df2ea647f6b8eaa88c77ac495659b262ffc15d1572ec59750a6e1a
          name: container-image
